name: responsive_adaptive_ui
description: A Flutter package for responsive and adaptive UIs (percent sizes, breakpoints, adaptive widgets).
version: 0.0.1
homepage: https://github.com/noumanzindani/responsive_adaptive_ui
repository: https://github.com/noumanzindani/responsive_adaptive_ui
issue_tracker: https://github.com/noumanzindani/responsive_adaptive_ui/issues


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
